### ISSUE TITLE
W2_Shiny: group conditions by ICD chapter

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/LongCovidStudyathon#1]
Like in this paper https://www.nature.com/articles/s41467-020-18849-z, it would be nice to group condition concepts by ICD chapter (allowing the user to colour by group, filter by group, etc)

**Comment by edward-burn** [comment]
This has the chapters from ICD along with names that we assign  https://github.com/oxford-pharmacoepi/LongCovidStudyathon/blob/main/W2_Characterization/ShinyAndFigures/data/chapters.csv - @ajoedicke @tiozab can you please review the choices of names (each one will be a group)

**Comment by tiozab** [comment]
added a new csv file called chapter_selecte.csv
