### ISSUE TITLE
W2 for Discussion: Any additional drugs for treatment pattern needed?

### ISSUE THREAD

**Issue by ajoedicke** [oxford-pharmacoepi/LongCovidStudyathon#13]
@nthtrinh

Do we need any additional drug classes that would be of particular interest for treatment pattern - also know that we want to characterise people with long COVID at the time they have their fist symptom/PASC condition recorded? 
We currently look at the following drugs/drug classes:

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/10808070/232747851-7fb96225-23c9-4a41-8aa2-ed7ed9dad093.png)

**Comment by nthtrinh** [comment]
Can you please clarify what does it mean by "other" in the table?

**Comment by mmayerp** [comment]
I am not sure if it is necessary to mention dexamethasone and corticosteroids and no other specific corticosteroids

**Comment by mmayerp** [comment]
Dexamethosone is one of the corticosteroids. Maybe we have to decide it is necessary or not to talk about corticosteroids in general.

**Comment by mmayerp** [comment]
Ivermectin was suggested as a drug for the treatment of COVID-19 but also to prevent long COVID

**Comment by mmayerp** [comment]
Statins are mentioned in some studies as a potential protective action in from of long COVID
