### ISSUE TITLE
W2 Additional analyses requested: Drug utilisation at the time of symptom

### ISSUE THREAD

**Issue by ajoedicke** [oxford-pharmacoepi/LongCovidStudyathon#14]
@KimLopezGuell and @catalamarti and @nmercadeb 

Can we please add another analysis: Can we run drug utilisation for the different drug windows for LC any + [inf, reinf, neg test and flu] and PASC any + [inf, reinf, neg test and flu] and LC CODE + [inf, reinf, neg test and flu]

Need to be checked with DB partners if we need amendments for this

**Comment by mmayerp** [comment]
Long COVID: major findings, mechanisms and recommendations (some general treatment recommendations)
https://www.nature.com/articles/s41579-022-00846-2

**Comment by corinslo** [comment]
Can you expand the time windows ?
In the characterization group 
-180;-1
-90;-1

In the drugs group
-180;-1
-90;-1
0;90
91;180
