### ISSUE TITLE
W2_Shiny: add smd when comparing cohorts

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/LongCovidStudyathon#7]
It would be nice if we could add a column with the SMDs when comparing cohorts. @catalamarti could you please paste some generic code for getting SMD for two proportions here (and I can then implement it in the shiny)

**Comment by catalamarti** [comment]
```
x <- x %>%
  dplyr::select("target_percentage", "comparator_percentage") %>%
  dplyr::mutate(
    p1 = .data$target_percentage,
    p2 = .data$comparator_percentage
  ) %>%
  dplyr::mutate(
    smd = (.data$p1 - .data$p2)/sqrt((.data$p1 * (1 - .data$p1) + .data$p2 * (1 - .data$p2)) / 2)
  ) %>%
  dplyr::select(-"p1", -"p2")
```
@edward-burn

**Comment by ajoedicke** [comment]
I dont think we need this for the manuscript at the moment. Will close issue for now.
